version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habitus-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/habitus-finance
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - habitus-network

  mongodb:
    image: mongo:latest
    container_name: habitus-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - habitus-network

  redis:
    image: redis:latest
    container_name: habitus-redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - habitus-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - app
    networks:
      - habitus-network

volumes:
  mongodb_data:
  redis_data:

networks:
  habitus-network:
    driver: bridge 