version: '3.8'

services:
  # Serviço de API FastAPI (Produção)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: habitus-forecast-api-prod
    container_name: habitus-forecast-api-prod
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/habitus-prod?authSource=admin
      - ENVIRONMENT=production
      - DEBUG=False
      - WORKERS=4
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongo
    networks:
      - habitus-network-prod
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]

  # Serviço de banco de dados MongoDB (Produção)
  mongo:
    image: mongo:6
    container_name: habitus-forecast-mongo-prod
    restart: always
    env_file:
      - .env.prod
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=habitus-prod
    volumes:
      - mongo-data-prod:/data/db
      - mongo-config-prod:/data/configdb
      - ./mongo-init.prod.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./backups:/backups
    expose:
      - 27017
    networks:
      - habitus-network-prod
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    command: ["--auth", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1.5"]
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  # Serviço de frontend React (Produção)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.client
      args:
        - REACT_APP_API_URL=https://api.habitus-forecast.com/api/v1
        - NODE_ENV=production
    image: habitus-forecast-frontend-prod
    container_name: habitus-forecast-frontend-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - habitus-network-prod
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Serviço de backup automático
  backup:
    image: mongo:6
    container_name: habitus-forecast-backup
    restart: always
    env_file:
      - .env.prod
    volumes:
      - ./backups:/backups
      - ./scripts/backup.sh:/usr/local/bin/backup.sh:ro
    networks:
      - habitus-network-prod
    depends_on:
      - mongo
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "chmod +x /usr/local/bin/backup.sh && 
       echo '0 0 * * * /usr/local/bin/backup.sh' > /etc/crontabs/root && 
       crond -f -d 8"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=habitus-prod
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - BACKUP_DIR=/backups

volumes:
  mongo-data-prod:
    name: habitus-mongo-data-prod
  mongo-config-prod:
    name: habitus-mongo-config-prod

networks:
  habitus-network-prod:
    driver: bridge 