version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: habitus-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=habitus
      - MONGO_INITDB_ROOT_PASSWORD=habitus123
    networks:
      - habitus-network

  redis:
    image: redis:latest
    container_name: habitus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - habitus-network

volumes:
  mongodb_data:
  redis_data:

networks:
  habitus-network:
    driver: bridge 