name: MongoDB Backup

on:
  schedule:
    - cron: '0 2 * * *'  # Executa todos os dias às 2h da manhã
  workflow_dispatch:      # Permite execução manual

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MongoDB tools
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '4.4'

      - name: Create backup
        run: |
          mkdir -p backup
          mongodump --uri=${{ secrets.MONGO_URI }} --out=backup
          tar -czf backup.tar.gz backup
          rm -rf backup

      - name: Upload backup
        uses: actions/upload-artifact@v2
        with:
          name: mongodb-backup
          path: backup.tar.gz 